import PlayerClient from "./PlayerClient";

interface SearchParams {
  u?: string;
  r?: string;
  e?: string;
  s?: string;
}

/**
 * /play
 *
 * Reads the signed query params from the bot's link and hands them to the
 * client component. We deliberately do NOT verify the signature here on the
 * server: verification happens at /api/stream when the actual fetch fires,
 * which is the only place where access matters. Letting the page render
 * either way keeps things simple and gives the user a clearer error if the
 * signature is bad (the video element fails to load instead of a 404 page).
 *
 * Param shorthand (kept short to keep links chat-friendly):
 *   u — video URL
 *   r — referer (optional; if omitted, the proxy uses the video's own origin)
 *   e — exp (unix seconds)
 *   s — sig (base64url HMAC)
 */
export default async function PlayPage({
  searchParams,
}: {
  searchParams: Promise<SearchParams>;
}) {
  const params = await searchParams;
  const u = params.u ?? "";
  const r = params.r ?? "";
  const e = params.e ?? "";
  const s = params.s ?? "";

  if (!u || !e || !s) {
    return (
      <main className="flex min-h-screen items-center justify-center px-6 text-center">
        <div className="max-w-md rounded-2xl border border-white/10 bg-white/[0.03] p-8 backdrop-blur">
          <h1 className="text-2xl font-semibold">Invalid link</h1>
          <p className="mt-3 text-sm text-fg-muted">
            This player only accepts signed URLs generated by the bot. Open
            the link from Telegram or generate a new one.
          </p>
        </div>
      </main>
    );
  }

  // If the upstream URL doesn't actually need a Referer (no `r` param),
  // the player streams it directly without the proxy hop. Saves bandwidth.
  const direct = !r;

  return (
    <PlayerClient
      videoUrl={u}
      referer={r || null}
      exp={Number(e)}
      sig={s}
      direct={direct}
    />
  );
}
