/**
 * Landing page.
 *
 * Public face of the player. Doesn't expose the extractor or any input —
 * playable links are only generated by the Telegram bot, which signs them
 * with a shared secret. Anyone visiting / directly just gets a brief
 * description and a button that opens the bot.
 */

const BOT_URL = process.env.NEXT_PUBLIC_BOT_URL || "https://t.me/";

export default function Home() {
  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col items-center justify-center px-6 py-16 text-center">
      <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs uppercase tracking-widest text-fg-muted backdrop-blur">
        <span className="size-1.5 rounded-full bg-emerald-400" />
        live
      </div>

      <h1 className="bg-gradient-to-br from-white via-white to-indigo-300 bg-clip-text pb-2 text-5xl font-semibold tracking-tight text-transparent sm:text-6xl">
        Doomsday Player
      </h1>

      <p className="mt-5 max-w-xl text-base leading-relaxed text-fg-muted">
        Browser playback for hotlink-protected videos. We forge the right
        Referer server-side so your CDN doesn&rsquo;t bounce the request.
        Works on iOS Safari, no app, no plugin.
      </p>

      <div className="mt-10 flex flex-col items-center gap-3 sm:flex-row">
        <a
          href={BOT_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="group inline-flex items-center gap-2 rounded-full bg-indigo-500 px-6 py-3 font-medium text-white shadow-[0_0_40px_-10px_rgba(99,102,241,0.6)] transition-all hover:bg-indigo-400 hover:shadow-[0_0_50px_-5px_rgba(99,102,241,0.8)]"
        >
          Open Telegram bot
          <span className="transition-transform group-hover:translate-x-0.5">
            →
          </span>
        </a>

        <span className="text-xs text-fg-muted">
          Player links are signed and expire automatically.
        </span>
      </div>

      <div className="mt-20 grid w-full grid-cols-1 gap-4 text-left sm:grid-cols-3">
        <Card title="Direct streams">
          MP4, WebM and similar files play with native controls and full seek
          support via HTTP Range.
        </Card>
        <Card title="HLS playlists">
          .m3u8 manifests are rewritten on the fly so every segment routes
          through the same proxy.
        </Card>
        <Card title="Signed links only">
          Each link from the bot embeds an HMAC signature with an expiry. We
          refuse anything else.
        </Card>
      </div>

      <footer className="mt-20 text-xs text-fg-muted">
        Built with Next.js. No tracking. Source on GitHub.
      </footer>
    </main>
  );
}

function Card({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 backdrop-blur transition-colors hover:border-white/20">
      <div className="mb-2 text-sm font-medium text-white">{title}</div>
      <div className="text-sm leading-relaxed text-fg-muted">{children}</div>
    </div>
  );
}
